### PR TITLE
Auto-detect & support `.sass` extension; provide default value for exclusion

### PR DESCRIPTION
**Pull request by drewlustro**
#### Hello!

🙌 Nice script! I tried to make this work for my project, but noticed it only worked with `.scss`. I tried to adapt it to my needs and while it didn't quite get there, I improved the script in a few ways.

### Highlights ✨ 
- Auto-detects extension `.scss|.sass`
  - Provides regex for extension
- Does not error out on undefined exclusions, fixing #1
- Provides a crude `test/` folder, containing a simplistic set of test files to run the script against
  - A proper test suite would actually compare the results against expected results
  - `npm test`

I would finish the test suite, but have to get back to normal work.

### CODE REVIEW

**Comment by sliptype** [comment]
Thank you @drewlustro! I really appreciate the contribution 😄

My only concern is that `detectedFileExtension` is global and not explicitly passed into the functions using it. Maybe we could do something like this:
* Make `detectedFileExtension` a local const in `sassShake`
* Pass `detectedFileExtension` into `traverseSassImportTree` and `findUnusedFiles`
* Combine the `sassFile`, `sassPartial`, and `possibleFilenames` functions into a `fileNameListFactory` function that is curried on `fileExtension`:
    ```
    const fileNameListFactory = (fileExtension) => (filename) => [
        fileName,
        `${filename}${fileExtension}`,
        `_${filename}${fileExtension}`
    ];
    ```
* In `traverseSassImportTree` create an instance of `fileNameListFactory` and use it instead of `possibleFilenames`:
    ```
    const makeFileNameList = fileNameListFactory(detectedFileExtension);
    ```

What do you think?

**Comment by drewlustro** [comment]
✅ Sounds good! Only piece i didn't 100% follow:

> `fileNameListFactory` function that is curried on `fileExtension`

I believe this adds unnecessary complication. It's tempting to curry endlessly in ES6+, but in this situation I think a simple extra parameter is better.

**Also:** I fixed your `eslint` configuration, applied a preset, and resolved all of the warnings 😄

**Comment by sliptype** [comment]
🤩 Really great work, can't thank you enough!

**Comment by drewlustro** [comment]
🙌

**Pull request merged**
